**Importing libraries**

In [ ]:
import pandas as pd
import numpy as np

**Importing Datset**

In [ ]:
dataset = pd.read_csv('housing.csv')
selected_features = ['RM','LSTAT','PTRATIO']

#Checking for any null values in the dataset
print(dataset.isnull().sum())

X = dataset[selected_features]
y = (dataset['MEDV'])

RM         0
LSTAT      0
PTRATIO    0
MEDV       0
dtype: int64


**Splitting into training and test sets**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train)

        RM  LSTAT  PTRATIO
447  6.209  13.22     20.2
457  5.427  18.14     20.2
386  5.349  19.77     20.2
361  6.380  23.69     20.2
221  6.552   3.76     17.4
..     ...    ...      ...
323  6.310   6.75     20.2
192  7.274   6.62     12.6
117  6.021  10.30     17.8
47   6.030  18.80     17.9
172  6.020  10.11     16.6

[391 rows x 3 columns]


**Applying feature scaling to our dataset**

In [ ]:
from sklearn.preprocessing import StandardScaler
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit and transform the scaler on the training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform the test data using the same scaler
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled)

[[-0.03187316  0.04649813  0.78568433]
 [-1.24840058  0.74833711  0.78568433]
 [-1.36974219  0.98085693  0.78568433]
 ...
 [-0.32433755 -0.37004046 -0.36758671]
 [-0.3103366   0.84248624 -0.31953375]
 [-0.32589321 -0.39714399 -0.94422223]]


In [ ]:
# Create and train a linear regression model on the scaled data
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# Make predictions on the scaled test set
y_pred = model.predict(X_test_scaled)

# Calculate the Mean Squared Error (MSE) on the test set
mse = mean_squared_error(y_test, y_pred)

# Report the MSE
print("Mean Squared Error on Test Set (with StandardScaler):", mse)

Mean Squared Error on Test Set (with StandardScaler): 9727501160.084394
